branch-defaults:
  master:
    environment: Udagramapi-env
global:
  application_name: udagram-api
  default_ec2_keyname: e-nddynnqzvy
  default_platform: Node.js 16 running on 64bit Amazon Linux 2/5.6.3
  default_region: us-east-1
  sc: git
deploy:
  artifact: www/Archive.zip